server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    # 是否要注册到其他Eureka Server实例
    registerWithEureka: false
    # 是否要从其他Eureka Server实例获取数据
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

  #server:
  #界面自我保护提示信息显示
  #  enable-self-preservation: false