server:
  port: 8771
spring:
  application:
    # 指定注册到eureka server上的服务名称，对于商品微服务，本系列将名称设为 product-service
    name: product-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      # 采样率，模式0.1，也就是10%，为了便于观察效果，改为1.0，也就是100%。生产环境建议保持默认。
      probability: 1.0
eureka:
  client:
    service-url:
      # 指定eureka server通信地址，注意/eureka/小尾巴不能少
      defaultZone: http://localhost:8761/eureka/
  instance:
    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
    prefer-ip-address: true